# Data Preprocessing with Python

In [69]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [70]:
dataset_location = "./files/Data.csv"

In [71]:
dataset = pd.read_csv(dataset_location)

In [72]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [73]:
x_data = dataset.iloc[:, : -1].values

In [74]:
y_labels = dataset.iloc[:, 3].values

In [75]:
x_data, y_labels

(array([['France', 44.0, 72000.0],
        ['Spain', 27.0, 48000.0],
        ['Germany', 30.0, 54000.0],
        ['Spain', 38.0, 61000.0],
        ['Germany', 40.0, nan],
        ['France', 35.0, 58000.0],
        ['Spain', nan, 52000.0],
        ['France', 48.0, 79000.0],
        ['Germany', 50.0, 83000.0],
        ['France', 37.0, 67000.0]], dtype=object),
 array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
       dtype=object))

## Ways of dealing with missing data? 1) Remove, 2) Create data, by putting in the mean.

In [76]:
# Taking care of missing data.

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy="mean")

In [77]:
x_data

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [78]:
imputer = imputer.fit(x_data[:, 1:3]) # 1:3 because, the indices are [)

In [79]:
x_data[:, 1:3] = imputer.transform(x_data[:, 1:3])

In [80]:
x_data

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

## Encoding categorical data

In [81]:
from sklearn.preprocessing import LabelEncoder
label_encoder_x = LabelEncoder()

In [82]:
x_data[:, 0] = label_encoder_x.fit_transform(x_data[:, 0])

In [83]:
x_data

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

### There is a problem with this, as the categorical values will have "numerical" order. That is, Germany is now > France. Here is where 'dummy encoding' comes in handy.

#### That is, have a column for each of the categorical values.

In [84]:
from sklearn.preprocessing import OneHotEncoder
one_hot_encoder = OneHotEncoder(categorical_features=[0])

In [85]:
x_data = one_hot_encoder.fit_transform(x_data).toarray()

c:\users\saqibur\appdata\local\programs\python\python37\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
c:\users\saqibur\appdata\local\programs\python\python37\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [86]:
x_data

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
        4.80000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 3.00000000e+01,
        5.40000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.37777778e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
        5.80000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
        5.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
        7.90000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e+01,
        8.30000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.70000000e+01,
        6.70000000e+04]])

## Need to encode the labels as well

In [87]:
label_encoder_y = LabelEncoder()
y_labels = label_encoder_y.fit_transform(y_labels)

In [88]:
y_labels

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

## Splitting the data into training and testing sets

In [89]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x_data, y_labels, test_size=0.25, random_state=0)

In [90]:
X_train, X_test, y_train, y_test

(array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.70000000e+01,
         6.70000000e+04],
        [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
         4.80000000e+04],
        [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
         5.20000000e+04],
        [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
         7.90000000e+04],
        [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
         6.10000000e+04],
        [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
         7.20000000e+04],
        [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
         5.80000000e+04]]),
 array([[0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 3.00000000e+01,
         5.40000000e+04],
        [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e+01,
         8.30000000e+04],
        [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
         6.37777778e+04]]),
 array

## Feature Scaling

In [91]:
from sklearn.preprocessing import StandardScaler
scaler_X = StandardScaler()

In [92]:
X_train = scaler_X.fit_transform(X_train)
X_test = scaler_X.fit_transform(X_test)

In [93]:
X_test, X_train

(array([[ 0.        ,  0.        ,  0.        , -1.22474487, -1.07298811],
        [ 0.        ,  0.        ,  0.        ,  1.22474487,  1.33431759],
        [ 0.        ,  0.        ,  0.        ,  0.        , -0.26132948]]),
 array([[ 0.8660254 ,  0.        , -0.8660254 , -0.2029809 ,  0.44897083],
        [-1.15470054,  0.        ,  1.15470054, -1.82168936, -1.41706417],
        [-1.15470054,  0.        ,  1.15470054,  0.08478949, -1.0242147 ],
        [ 0.8660254 ,  0.        , -0.8660254 ,  1.5775984 ,  1.62751925],
        [-1.15470054,  0.        ,  1.15470054, -0.04111006, -0.14030338],
        [ 0.8660254 ,  0.        , -0.8660254 ,  0.93011502,  0.94003267],
        [ 0.8660254 ,  0.        , -0.8660254 , -0.52672259, -0.43494049]]))